name: 更新001
 
on:
  schedule:
    - cron: '59 23 * * *'  # 每天凌晨2点执行
    #- cron: '*/5 * * * *'  # 每分钟执行
  workflow_dispatch:
    
jobs:
  update_txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git
      run: |
        git config --global user.email "474628725@qq.com"
        git config --global user.name "smile"
    - name: Update txt file
      run: |
        python new/001.py 
        git add new/xj_tv.m3u
        git commit -m "Update 0.txt"
        git push
