name: 福音影视--更新
# 触发条件
on:
  # push的时候触发
  # push:
  #   branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
    - cron: 30 3 * * 1,4
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: 加载缓存  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务
      run: |
        python IPTV_PY/FYYS_ZR.py
    - name: 检测文件是否更新
      id: check_updates
      run: | 
        git status --porcelain
        # 测试 grep
        git_output="M \"IPTV_M3U/\347\237\275\350\260\267\345\237\272\347\235\243\345\276\222\350\201\232\344\274\232.m3u\"\n M \"SJ_JSON/\347\246\217\351\237\263\345\275\261\350\247\206.json\""
        grep_result=$(echo "$git_output" | grep -E '^(M|A|D|R|C)')
        echo "Grep result: $grep_result"

        # 测试 awk
        awk_result=$(echo "$grep_result" | awk 'BEGIN {RS="\n"; FS=" "} {if ($1 ~ /^(M|A|D|R|C)/) print $2}')
        echo "Awk result: $awk_result"
         
        UPDATED_FILES=$(git status --porcelain | grep -E '^(M|A|D|R|C)' | awk '{print $2}')
        echo "UPDATED_FILES: $UPDATED_FILES"
        if [ -z "$UPDATED_FILES" ]; then
          echo "No updated files. Skipping git add."
          exit 0
        fi 
    - name: 提交更改
      run: |    
         git pull origin main
         git config --local user.email "474628725@qq.com"
         git config --local user.name "badboy518714"
         git add .
         git commit -m "由github actions推送更新,日期:`date`"
    # - name: 检测文件是否更新
    #   id: check_updates
    #   run: |        
    #     UPDATED_FILES=$(git status --porcelain | grep -E '^(M|A|D|R|C)' | awk '{print $2}')
    #     if [ -z "$UPDATED_FILES" ]; then
    #       echo "No updated files. Skipping git add."
    #       exit 0
    #     fi 
    - name: 推送更改
      if: steps.check_updates.outputs.UPDATED_FILES!= ''
      uses:  ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
