name: js调试

on:
  # push的时候触发
  push:
    paths:
      - 'IPTV_JS/js/df_live.js'
  workflow_dispatch:
  # 定时触发
  # schedule:
  #   - cron: 30 2 * * *
jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0'
    - name: Run JavaScript file
      run: node --experimental-modules IPTV_JS/js/df_live.js
