name: 圣经--更新
# 触发条件
on:
  # push的时候触发
  # push:
  #   branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
    - cron: 30 2,14 * * 1,4
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: 加载缓存  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务
      run: |
        python ./IPTV_PY/SJ.py
          
    - name: 提交更改
      env:
        GITHUB TOKEN: ${{ secrets.TOKEN }}
      run: |     
         git pull origin main
         git config --local user.email "474628725@qq.com"
         git config --local user.name "badboy518714"
         git add ./IPTV_M3U/SJ_HW.m3u
         git add ./IPTV_M3U/SJ_FT.m3u
         git add ./SJ_JSON/SJ_HW.json
         git add ./SJ_JSON/SJ_FT.json
         git commit -m "由github actions推送更新圣经m3u文件,日期:`date`"
    - name: 推送更改
      run: | 
         git push
